version: "3.5"

services:
 boilerplate-nestjs-docker:
  container_name: boilerplate-nestjs-docker
  # build: 
  #    context: .
  #    dockerfile: Dockerfile.prod
  image: gabrielsoaresdev/boilerplate-nestjs-docker:latest
  restart: always
  ports:
   - "3005:3005"
  networks:
   - boilerplate-nestjs-docker-network
  env_file:
    - stack.env
networks:
  boilerplate-nestjs-docker-network:
   name: boilerplate-nestjs-docker-network
   driver: bridge